# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39587358e70fbe8381a654de3ba198ff2959be43bdb1d019b0e43767479606f198e8760be3834f08a702f7a8fb4b6ae17f2bd5b2426209f2ba2999a86f51b71

test:
  secret_key_base: c196249e9d4e2e461def0ffa897fb6f98752d28ffc4008594e7a6c41beb575a5f7c054cfe0518e2e485cea11d4dfaa58a23e1df1683065f1d1e391000645cdbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
